basePath: /api/v1
definitions:
  model.WebResponse:
    properties:
      code:
        type: integer
      message: {}
      status:
        type: string
    type: object
  request.CreatePPPoERequest:
    properties:
      password_pppoe:
        type: string
      profile_pppoe:
        type: string
      remote-address_pppoe:
        type: string
      router_ip_addr:
        type: string
      router_password:
        type: string
      router_username:
        type: string
      username_pppoe:
        type: string
    required:
    - password_pppoe
    - profile_pppoe
    - remote-address_pppoe
    - router_ip_addr
    - router_password
    - router_username
    - username_pppoe
    type: object
  request.DeletePPPoERequest:
    properties:
      remote-address_pppoe:
        type: string
      router_ip_addr:
        type: string
      router_password:
        type: string
      router_username:
        type: string
    required:
    - remote-address_pppoe
    - router_ip_addr
    - router_password
    - router_username
    type: object
host: localhost:3000
info:
  contact:
    email: danu@megadata.net.id
    name: Megadata Pemalang
    url: https://github.com/megadata-dev
  description: This is a sample server for RouterOS v7 Service API Documentation.
  license:
    name: MIT
    url: https://github.com/megadata-dev/routerosv7-service/blob/main/LICENSE
  title: RouterOS v7 Service API Documentation
  version: 1.0.0
paths:
  /ppp/secret/add:
    post:
      consumes:
      - application/json
      description: Add PPP Secret
      parameters:
      - description: Add PPP Secret
        in: body
        name: pppSecret
        required: true
        schema:
          $ref: '#/definitions/request.CreatePPPoERequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.WebResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.WebResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.WebResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.WebResponse'
      summary: Add PPP Secret
      tags:
      - PPP
  /ppp/secret/delete:
    delete:
      consumes:
      - application/json
      description: Delete PPP Secret
      parameters:
      - description: Delete PPP Secret
        in: body
        name: pppSecret
        required: true
        schema:
          $ref: '#/definitions/request.DeletePPPoERequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/model.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.WebResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.WebResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.WebResponse'
      summary: Delete PPP Secret
      tags:
      - PPP
swagger: "2.0"
